const path = require('path');

module.exports = {
  API_VERSION: '0.0.1',
  
  GQL_PORT: 4000,
  SECRET_KEY : 'secret key',
  AUTH_ALGORITHM: 'RS256',

  GRID_SERVICE_PUBLIC_KEY_FILE: process.env['METRIFFIC_GRID_SERVICE_PUBLIC_KEY_FILE'],
  GRID_SERVICE_ENDPOINT: 'grid_service',

  WORKSPACE_MANAGER_PUBLIC_KEY_FILE: process.env['METRIFFIC_WORKSPACE_MANAGER_PUBLIC_KEY_FILE'],
  WORKSPACE_MANAGER_ENDPOINT: 'workspace_manager',

  AUTHENTICATION_MANAGER_PUBLIC_KEY_FILE: process.env['METRIFFIC_AUTHENTICATION_MANAGER_PUBLIC_KEY_FILE'],
  AUTHENTICATION_MANAGER_ENDPOINT: 'authentication_manager',

  DATABASE_FILE: process.env['METRIFFIC_DB_FILE'],
}
